### ISSUE TITLE
Create endpoint to retrieve a space

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#100]
## Description

A REST API endpoint to retrieve one space needs to be build.

_This ticket is about version 1 of the API._

## Acceptance criteria

- An endpoint is available to retrieve one space by its ID.
- The response contains the data of the space according to the resource data contract.

### Tasks

- [x] Create new controller action `SpaceController@show` in `App\API\V1\Http\Controllers`.
- [x] Create feature test for the `show` endpoint
- [x] Use resource from #99.

**Comment by cyrildewit** [comment]
This ticket is blocked because I'm waiting for #99
