### ISSUE TITLE
Create endpoint to retrieve a user

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#105]
## Description

A REST API endpoint to retrieve one user needs to be build. This way the mobile Repair Tool application can fetch data of a user. This endpoint should return different data sets based on permissions. If the authorised user is for example not the same as the requested user, other permissions should be checked first before returning the whole date. If authorised user does not have the rights to view someone else profile, he should only receive the public data set. This is necessary to show information about a user within the application. For example the profile of the current building manager.

_This ticket is about version 1 of the API._

## Acceptance criteria

- An endpoint is available to retrieve one space by its ID.
- The response contains the data of the space according to the resource data contract.

### Tasks

- [x] Work out a good solution to present different data sets of a resource. What are the best practices?
- [x] Create new controller action `UserController@show` in `App\API\V1\Http\Controllers`.
- [x] Create feature test for the `show` endpoint
- [x] Use resource from #99.
