### ISSUE TITLE
Extend code review list with REST API documentation practises

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#110]
## Description

We require that every change to the REST API is reflected in the OpenAPI documentation. We should add this to our list of code review rules.

## Design

If we setup an GitHub pages website like we did for the guides, then we can create a contributing section. Within this section, we can describe our general practises for the REST API.

## Tasks

- [x] Create REST API page in contributing directory
- [x] Document a little about where the code is located in the repostitory
- [x] Document that the OpenAPI description files must be kept up to date with the REST API implementation

**Comment by cyrildewit** [comment]
![REST API - Core Application](https://user-images.githubusercontent.com/16477999/168662605-cc6e1d7f-208c-4529-9d99-0a8c1b8c5e8b.png)
