### ISSUE TITLE
Create group resource transformer for REST API version 1

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#111]
## Description

New REST API endpoints will be created in the following week(s). One common implementation that's needed, before these tickets can be picked up is the `GroupResource` resource.

## Acceptance criteria

- A group resource class is available.
- The group resource data contract is validated by tests.

### Tasks

- [x] Create/Extend API resource `GroupResource` in `App\API\V1\Http\Resources` to transform the Eloquent model
- [x] Create/Extend API resource `GroupCollection` in `App\API\V1\Http\Resources`
- [x]  Create/Extend API resource `GroupTypeResource` in `App\API\V1\Http\Resources` to transform the Eloquent model
- [x] Create feature test to assert the data contract of the `GroupResource` resource
- [x] Create feature test to assert the data contract of the `GroupTypeResource` resource

#### `GroupResource` resource

```yml
  schemas:
    Space:
      type: object
      properties:
        id:
          type: integer
          format: bigint20
        name:
          type: string
        group_type_id:
          type: bigint20
        created_at:
          type: string
        updated_at:
          type: string
      required:
        - id
        - name
```
