### ISSUE TITLE
Create endpoint to list all groups

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#112]
## Description

A REST API endpoint to get all groups is needed. This endpoint should be able to handle filters, sorts and includes.

_This ticket is about version 1 of the API._

## Acceptance criteria

- An endpoint is available to list all groups.
- The response is paginated according to the JSON:API specification to prevent big and slow responses.
- Filtering can be applied for the following columns:
  - `name` (partial)
  - `group_type_id` (partial)
- Sorting can be applied for the following columns:
  - `created_at`
  - `updated_at`

### Tasks

- [x] Create new controller action `GroupController@index` in `App\API\V1\Http\Controllers`.
- [x] Create feature test for the `index` endpoint
- [x] Use resource from #111.
