### ISSUE TITLE
Create endpoint to update a group

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#115]
## Description

A REST API endpoint to update one group needs to be build.

_This ticket is about version 1 of the API._

## Acceptance criteria

- An endpoint is available to update one group by its ID.
- The response contains the data of the group according to the resource data contract.

### Tasks

- [ ] Create new controller action `GroupController@update` in `App\API\V1\Http\Controllers`.
- [ ] Create feature test for the `update` endpoint
- [ ] Use resource from #111.

### Design
