### ISSUE TITLE
Create endpoint to list all reservations

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#118]
## Description

A REST API endpoint to get all reservations is needed. This endpoint should be able to handle filters, sorts and includes.

_This ticket is about version 1 of the API._

## Acceptance criteria

- An endpoint is available to list all reservations.
- The response is paginated according to the JSON:API specification to prevent big and slow responses.
- Filtering can be applied for the following columns:
  - ~`starts_at`~ (these are skipped for now since it requires more research in how we will be creating filters for dates)
  - ~`ends_at`~ these are skipped for now since it requires more research in how we will be creating filters for dates)
  - `space_id` (exact)
  - `group_id` (exact)
  - `created_by_user_id` (exact)
- Sorting can be applied for the following columns:
  - `starts_at`
  - `ends_at`
  - `created_at`
  - `updated_at`

### Tasks

- [x] Create new controller action `ReservationController@index` in `App\API\V1\Http\Controllers`.
- [x] Create feature test for the `index` endpoint
- [x] Use resource from #117.
