### ISSUE TITLE
Create endpoint to retrieve a reservation

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#119]
## Description

A REST API endpoint to retrieve one group needs to be build.

_This ticket is about version 1 of the API._

## Acceptance criteria

- An endpoint is available to retrieve one reservation by its ID.
- The response contains the data of the group according to the resource data contract.

### Tasks

- [x] Create new controller action `ReservationController@show` in `App\API\V1\Http\Controllers`.
- [x] Create feature test for the `show` endpoint
- [x] Use resource from #117.
