### ISSUE TITLE
Create endpoint to update a reservation

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#121]
## Description

A REST API endpoint to update one reservation needs to be build.

_This ticket is about version 1 of the API._

## Acceptance criteria

- An endpoint is available to update one reservation by its ID.
- The response contains the data of the reservation according to the resource data contract.

### Tasks

- [x] Create new controller action `ReservationController@update` in `App\API\V1\Http\Controllers`.
- [x] Create feature test for the `update` endpoint
- [x] Use resource from #111.

### Design
