### ISSUE TITLE
Create endpoint to store a reservation

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#122]
## Description

A REST API endpoint to store a space needs to be build.

_This ticket is about version 1 of the API._

## Acceptance criteria

- An endpoint is available to store a reservation.
- The response contains the data of the reservation according to the resource data contract.

### Tasks

- [x] Validate request data.
- [x] Create new controller action `ReservationController@store` in `App\API\V1\Http\Controllers`.
- [x] Create feature test for the `store` endpoint
- [x] Use resource from #111.

### Design
