### ISSUE TITLE
Improve onboarding of new contributors to this project

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#142]
## Description

To make this project more open for new contributors, we should analyse the bottlenecks for them and come up with a solution.

### Purpose of this application

When I look at the readme it's not clear what the big picture is of this project. What is its place in the overall infrastructure. What does the application contains? A REST API, web application and the shared domain and business logic.

### Use of Docker

The setup section does not cover the requirement of having Docker locally installed.

### Which services are needed to run the application locally

It could be useful to document which services are needed to run the application locally. Maybe document the credentials to connect to the database for example.

###  Status of tests could be shown on the homepage

We could add the status of the tests action in the readme.

https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

### License is unclear and missing

The license is maybe not completely accurate. It should be:

> Copyright (c) KA-Huis. All rights reserved.
> Licensed under the MIT license.

### No dedicated contributing guide

The readme is now both covering generic and contributing information about the project. If we split these into different sections or files, it would be easier to read.

### Tasks

- [x] Add logo to readme
- [x] Improve introduction in readme
- [x] Add actions badge of tests to readme
- [x] Improve license notice
- [x] Add technical overview of the system
- [x] Improve installation steps
  - [x] Document which services are used
  - [x] Document that docker is used by default
  - [x] Add documentation about the seeded data
