### ISSUE TITLE
Make advice report about hosting providers

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#25]
## Tasks

- [x] 1. Write introduction
- [x] 2. Write about which hosting type is preferable
- [x] 2.1 Shared hosting
- [x] 2.2. VPS-hosting
- [x] 2.3. Dedicated hosting
- [x] 2.4 Conclusion
- [x] 3.  Hostingaanbieders
- [x] 3.1. Vultr
- [x] 3.2. DigitalOcean
- [x] 3.3. Hostwinds
- [x] 3.4 Linode
- [x] 3.5 UpCloud
- [x] 3.6 TransIP
- [x] 3.7 Google Cloud
- [x] 3.8 Amazon Web Services
- [x] 3.9 Microsoft Azure
- [x] 3.10 RamNode
- [x] 3.11 Hostnet
- [x] 5. Conclusie
- [ ] Samenvatting schrijven voor businessmensen (management)

**Comment by cyrildewit** [comment]
Summary of my conversation with @Hoopless:
* Start with creating an advice report that we can present to the stakeholders
* Extend requirements of desired hosting provider: Germany over London for example. If the hosting provider has a customer friendly control panel available that can be used by non-it'ers (important for the non-profit organization)

**Comment by cyrildewit** [comment]
@Hoopless and I worked today on the advice report. We've added it to our Fontys Canvas portfolio and requested feedback.

**Comment by cyrildewit** [comment]
Based on feedback from Leon, it will be really useful to write a summary for business people.
