### ISSUE TITLE
Setup REST API OAuth authorization

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#41]
## Description

There are different authorization specifications available. We will be using OAuth 2.0 protocol to manage authorization for our REST API. It is broadly used and has proven to be a good framework.

One of the benefits of this specification is the splitting of the roles. We can for example outsource the authorisation API to its own server or a third-party SaaS.

Another feature is the ability to defines scopes.

### Resources

1. [OAuth 2.0: An Overview](https://www.youtube.com/watch?v=CPbvxxslDTU )

## Technical input

The official [Laravel-package Passport](https://laravel.com/docs/9.x/passport) will be sufficient to set up OAuth for our application.

## Acceptance criteria

- [x] A HTTP middleware is available to protect routes for a specific guard

### Tasks

- [x] Install latest version of Passport
- [x] `Create table `api_users`~
- [x] ~Setup new authentication guard with `api_users` as data source~
- [x] Create OAuth client
- [x] Define oauth api routes
- [x] https://github.com/KA-Huis/space-management/pull/51/files#r847821052

### OAuth routes

Output form `php artisan route:list`.

```bash
GET|HEAD  login/oauth/authorize ............... passport.authorizations.authorize › Laravel\Passport › AuthorizationController@authorize
POST      login/oauth/authorize ............ passport.authorizations.approve › Laravel\Passport › ApproveAuthorizationController@approve
DELETE    login/oauth/authorize ..................... passport.authorizations.deny › Laravel\Passport › DenyAuthorizationController@deny
GET|HEAD  login/oauth/clients ..................................... passport.clients.index › Laravel\Passport › ClientController@forUser
POST      login/oauth/clients ....................................... passport.clients.store › Laravel\Passport › ClientController@store
PUT       login/oauth/clients/{client_id} ......................... passport.clients.update › Laravel\Passport › ClientController@update
DELETE    login/oauth/clients/{client_id} ....................... passport.clients.destroy › Laravel\Passport › ClientController@destroy
GET|HEAD  login/oauth/personal-access-tokens . passport.personal.tokens.index › Laravel\Passport › PersonalAccessTokenController@forUser
POST      login/oauth/personal-access-tokens ... passport.personal.tokens.store › Laravel\Passport › PersonalAccessTokenController@store
DELETE    login/oauth/personal-access-tokens/{token_id} passport.personal.tokens.destroy › Laravel\Passport › PersonalAccessTokenContro…
GET|HEAD  login/oauth/scopes ............................................ passport.scopes.index › Laravel\Passport › ScopeController@all
POST      login/oauth/token ....................................... passport.token › Laravel\Passport › AccessTokenController@issueToken
POST      login/oauth/token/refresh ....................... passport.token.refresh › Laravel\Passport › TransientTokenController@refresh
GET|HEAD  login/oauth/tokens ........................ passport.tokens.index › Laravel\Passport › AuthorizedAccessTokenController@forUser
DELETE    login/oauth/tokens/{token_id} ........... passport.tokens.destroy › Laravel\Passport › AuthorizedAccessTokenController@destroy

```

**Comment by cyrildewit** [comment]
I've gone over my design with @Hoopless. We've decided to remove the `ApiUser` abstraction and only use one `User` model. This is similar to how GitHub does it.
