### ISSUE TITLE
[BLOCKED] Research current webhosting infrastructure and services

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#73]
### Context

In order to be able to deploy the application(s) to production, we should research the current IT-infrastructure related to the website and used services.

### Current hosting company

The current website is hosted by [Direct Web Solutions B.V.](https://www.directwebsolutions.nl/webapplicatie-ontwikkeling/).

## Tasks

* [x] Where is the current site hosted?
* [ ] Is the current hoster offering this service for free?
* [ ] Is the current hoster open for changes to the infrastructure or should we chose for a new hosting provider?
* [ ] Where is the domain hosted? And how can we make adjustments to this?

**Comment by cyrildewit** [comment]
Enno will discuss with his team if they for example want to continue with the current hosting solution.

**Comment by cyrildewit** [comment]
Blocked, because we're waiting for a response from Enno.
