### ISSUE TITLE
Frontend and Backend meeting 28 april keypoints

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#89]
## Preparation

The goal of the meeting is to work out a plan to implement parts of the design using user stories. This way the goal stays the same between the team. 

First we should decompose the design. We can do this using user stories or other methods. We'll find and choose a technique on the spot. 

After we've decomposed everything, we can start with prioritising the tickets based on the most added value and shortest implementation time. Some tasks unfortunely needs to be done in order to move on, but that's fine.

Once we've created the initial plan with a focussed start, both teams can start with te tickets and work with each other to professionaly finish the tickets. 

### 

- [x] Outworking of technical dept of the design.

**Comment by cyrildewit** [comment]
# Meeting notes

We will all focus on the repair tool. 

The portals will be designed in the same style and all features will be build in one portal. Features will be enabled based on permissions.

## Tasks for frontend team

- [x] Choose which frontend framework they will use: React.js, Vue.js or Svelte
- [ ] Choose which CSS framework will be used


## Tasks for backend team

- [x] https://github.com/KA-Huis/space-management/issues/97 Create three oauth clients for @MiKessels, @Prupke @joeyvonck 
- [x] Work out roles #79 
- [x] Extend REST API with endpoints to manage spaces
- [x] Extend REST API with endpoints to get a user
- [x] Extend REST API with endpoints to manage groups
- [x] Extend REST API with endpoints to manage reservations
- [x] Create logic to determine if a reservation spot is free
- [x] Create logic to create a reservation

## Tasks for Android team
- [x] https://github.com/KA-Huis/repair-tool/issues/35

**Comment by cyrildewit** [comment]
Creating policy classes for common classes is also a good preparation. I've created tickets for the most important ones.
